# Generated by Django 5.0.1 on 2024-05-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_like_unique_together_like_unique_user_like_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
