# Generated by Django 5.0.1 on 2024-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_post_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
