# Generated by Django 5.0.1 on 2024-06-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology_used',
        ),
    ]
