# Generated by Django 5.0.1 on 2024-06-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_project_slug_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_link',
        ),
    ]
