# Generated by Django 5.0.1 on 2024-06-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_technology_remove_project_status_project_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='logoUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
